// Code generated by "stringer -type=Regconfig"; DO NOT EDIT.

package pqtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Arabic-13068]
	_ = x[Danish-13070]
	_ = x[Dutch-13072]
	_ = x[English-13074]
	_ = x[Finnish-13076]
	_ = x[French-13078]
	_ = x[German-13080]
	_ = x[Greek-13082]
	_ = x[Hungarian-13084]
	_ = x[Indonesian-13086]
	_ = x[Irish-13088]
	_ = x[Italian-13090]
	_ = x[Lithuanian-13092]
	_ = x[Nepali-13094]
	_ = x[Norwegian-13096]
	_ = x[Portuguese-13098]
	_ = x[Romanian-13100]
	_ = x[Russian-13102]
	_ = x[Spanish-13104]
	_ = x[Swedish-13106]
	_ = x[Tamil-13108]
	_ = x[Turkish-13110]
}

const _Regconfig_name = "ArabicDanishDutchEnglishFinnishFrenchGermanGreekHungarianIndonesianIrishItalianLithuanianNepaliNorwegianPortugueseRomanianRussianSpanishSwedishTamilTurkish"

var _Regconfig_map = map[Regconfig]string{
	13068: _Regconfig_name[0:6],
	13070: _Regconfig_name[6:12],
	13072: _Regconfig_name[12:17],
	13074: _Regconfig_name[17:24],
	13076: _Regconfig_name[24:31],
	13078: _Regconfig_name[31:37],
	13080: _Regconfig_name[37:43],
	13082: _Regconfig_name[43:48],
	13084: _Regconfig_name[48:57],
	13086: _Regconfig_name[57:67],
	13088: _Regconfig_name[67:72],
	13090: _Regconfig_name[72:79],
	13092: _Regconfig_name[79:89],
	13094: _Regconfig_name[89:95],
	13096: _Regconfig_name[95:104],
	13098: _Regconfig_name[104:114],
	13100: _Regconfig_name[114:122],
	13102: _Regconfig_name[122:129],
	13104: _Regconfig_name[129:136],
	13106: _Regconfig_name[136:143],
	13108: _Regconfig_name[143:148],
	13110: _Regconfig_name[148:155],
}

func (i Regconfig) String() string {
	if str, ok := _Regconfig_map[i]; ok {
		return str
	}
	return "Regconfig(" + strconv.FormatInt(int64(i), 10) + ")"
}
